name: Python CI for PyQt5 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This tells GitHub to run the job on a computer using Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # This gets the latest version of your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Using Python 3.11 as you mentioned

      - name: Check Python version
        run: |
          python3 --version  # Check if python3 is correctly installed
          pip --version  # Check if pip is correctly installed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pyqt5  # Install your system-wide dependencies
          
      - name: Verify Python and pip installation
        run: |
          which python3  # Check the path where python3 is installed
          which pip  # Check the path where pip is installed

      - name: Install Python dependencies from requirements.txt
        run: |
          python3 -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the app (just check if it starts)
        run: |
          python3 asap-cabinet-fe.py  # Use python3 explicitly to run the script
