name: Python CI for PyQt5 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Check Python version
        run: |
          python3 --version
          pip --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pyqt5

      - name: Verify Python and pip installation
        run: |
          which python3
          which pip

      - name: Install Python dependencies from requirements.txt
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if PyQt5 is installed
        run: |
          python3 -c "import PyQt5"

      - name: Run the app (just check if it starts)
        run: |
          python3 asap-cabinet-fe.py
