name: Python CI for PyQt5 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyqt5 libpulse-mainloop-glib0 pulseaudio
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start pulseaudio daemon
        run: |
          pulseaudio --start

      - name: Create directories and files for testing
        run: |
          mkdir -p /home/runner/Games/vpinball/build/tables/test
          touch /home/runner/Games/vpinball/build/tables/test/test_file.vpx
          touch /home/runner/Games/vpinball/VPinballX_GL

      - name: Set QT_QPA_PLATFORM to offscreen
        run: |
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

      - name: Run the app (just check if it starts)
        env:
          CI: "true"
        run: |
          python3 asap-cabinet-fe.py
